aula-app/aula-frontend

- src/components/ReportCard/ReportCard.tsx
- src/services/users.ts
Fix #643
Needs to have https://github.com/aula-app/aula-backend/pull/179 merged to work
> Also accepts requests from Reports content for change user displayname

- CHANGELOG.md
- package.json
Update Changelog and app versioning
> update CHANGELOG and app versioning

- tests/aula.login.spec.ts
- tests/example.spec.ts
- tests/fixtures/users.ts
- tests/mutating/main/categories.spec.ts
- tests/mutating/main/change_pass.spec.ts
- tests/mutating/main/users_csv_and_delete.spec.ts
- tests/shared/page_interactions/boxes.ts
- tests/shared/page_interactions/browsers.ts
- tests/shared/page_interactions/ideas.ts
- tests/shared/page_interactions/rooms.ts
- tests/shared/page_interactions/users.ts
- tests/shared/shared.ts
Claude Code broke the tests removing some necessary `export`'s. this PR revert that.
> Revert tests folder removing wrong AI changes

- src/views/Public/Login/LoginView.tsx
- src/views/Public/Recovery/RecoveryView.tsx
- src/views/Public/SetPassword/SetPasswordView.tsx
Reviewed the form handlers and identified 3 forms needing fixes.
> 686 login by pressing enter key

- src/layout/SideBar/SideBarContent.tsx
Added trigger navigation by pressing enter on menu
> trigger navigation by pressing enter on menu

- src/utils/index.ts
- src/utils/permissions.ts
Last merges broke build and tests due to a merge conflict. This PR reviews the code and fixes errors.
> Fix utils export

- .env.dev
> fix: turn off oauth on dev branch

- .github/workflows/dev.yml
> fix: dev branch workflow

- src/components/ImageEditor/ImageEditor.tsx
- src/components/UserAvatar/UserAvatar.tsx
> fix: add api/ to the image path

- src/services/consent.ts
> lower case aula-instance-code header

- src/components/ImageEditor/ImageEditor.tsx
- src/components/UserAvatar/UserAvatar.tsx
- src/services/consent.ts
> Simplify multi instances deployment 

- src/utils/localStorage.ts
> fix: api_url baseurl

- src/services/comments.ts
- src/services/ideas.ts
> fix display order by creation date

- src/views/Public/Recovery/RecoveryView.tsx
- src/views/Public/SetPassword/SetPasswordView.tsx
- [] Doesn't need update in the database or BE
> Get instance code from url on password recovery and user registration

- src/components/AppIconButton/AppIconButton.tsx
- src/components/Buttons/LikeButton/LikeButton.tsx
- src/components/Idea/CommentBubble/CommentBubble.tsx
- src/components/Idea/IdeaBubble/IdeaBubble.tsx
- src/utils/permissions.ts
fix permissions to prevent self likes
- [ x ] Tested manually 
- [ x ] GitHub issue linked 
- [ x ] Backward and forward compatible with BE 
- [ x ] Doesn't need update in the database or BE
> Disable likes for serf

- index.html
- src/index.css
removed roboto google font request
> Review font hierarchy

- src/index.css
- src/views/Settings/Config/ConfigView.tsx
- src/views/Settings/Profile/UserProfileView.tsx
> fix overscroll

- src/components/DataTable/DataItem.tsx
Manage markdown rendering on settings tables
> 683 escape characters rendered

- CHANGELOG.md
- src/components/DataFields/GroupField.tsx
- src/components/DataFields/UserField.tsx
Message forms where broken by invalid aria and ids on autocomplete fields.
> fix userField and GroupField on message forms

- src/views/Phases/PhasesView.tsx
- src/views/Welcome/DashBoard/index.tsx
- src/views/Welcome/Dashboard.tsx
- src/views/Welcome/WelcomeView.tsx
There was missing aria labels and other accessibility features on dashboard.
Other minor readability an maintainability improvements where added.
> fix: Improve welcome view accessibility

- src/components/DataDelete/DataDelete.tsx
- src/components/DataFields/IconField.tsx
- src/components/DataForms/RoomForms.tsx
- src/views/BoxPhase/BoxPhaseView.tsx
- src/views/Settings/Config/Categories/Categories.tsx
- src/views/Settings/Config/SchoolDelete/SchoolDelete.tsx
- src/views/Settings/Rooms/RoomsView.tsx
- tests/mutating/after/admin_announcements.spec.ts
- tests/mutating/main/categories.spec.ts
- tests/mutating/main/request_user_data.spec.ts
- tests/mutating/main/users_csv_and_delete.spec.ts
- tests/shared/page_interactions/rooms.ts
- tests/shared/page_interactions/users.ts
Fixed tests and changed text selectors to test-id specific selectors, granting better practices
> fix: tests

- CHANGELOG.md
- src/components/DataTable/DataItem.tsx
- src/hooks/date.ts
Time zones where not being considered on time display, so all time where UTC 0. Now, time is being converted to local time zones on display
> fix time display considering user's timezone

- src/components/AppIcon/AppIcon.tsx
- src/components/Buttons/ShareButton/ShareButton.tsx
- src/components/Buttons/ShareButton/index.tsx
- src/components/Idea/IdeaBubble/IdeaBubble.tsx
- src/locale/de.json
- src/locale/en.json
Share button was pointing to the wrong url
> Fix: correct share link path

- CHANGELOG.md
- src/views/BoxPhase/BoxPhaseView.tsx
> chore(changelog): update changelog

- src/locale/de.json
- src/locale/en.json
- src/views/BoxPhase/BoxPhaseView.tsx
- src/views/Comment/CommentView.tsx
- src/views/Idea/IdeaView.tsx
- src/views/Phases/PhasesView.tsx
- src/views/WildIdeas/WildIdeasView.tsx
Search Form disappears on empty search
> FIX: filtering of room phase views breaks when no results

- tests/mutating/main/reporting.spec.ts
- tests/mutating/main/request_user_data.spec.ts
- tests/shared/helpers/reporting.ts
- tests/shared/helpers/request-user-data.ts
- Break down a large test into a sequence of smaller tests
- Organize code
- Add cleanup procedures on error
> improve request tests

- src/components/ReportCard/ReportCard.tsx
- src/views/Messages/UserMessagesView.tsx
- tests/mutating/main/users_csv_and_delete.spec.ts
- tests/mutating/main/voting.spec.ts
- tests/shared/helpers/request-user-data.ts
- Break down a large test into a sequence of smaller tests
- Organize code
- Add cleanup procedures on error
- Remove Hardcoded text
- Review Manual file handling - Direct fs operations without proper cleanup
- Add error handling
- Improve sequential dependencies without shared context
- Fix Browser resource leaks - Manual browser/context management
> Feat: improve user_csv tests

- .github/workflows/pr-deploy.yml
> fix(cicd): fail the step and the job, but not the workflow

- tests/mutating/setup-auth.ts
- tests/shared/shared.ts
> fix: missing test-id.txt file error on setup

- LICENSE.txt
- README.md
- docs/INDEX.md
The management of "aula gGmbH" has made a decision on licensing the software in this repository. This PR updates the documentation.
Recently we discussed the point about using LLMs - this license setup grants the copyright holder to freely make decisions about submitting its own software to proprietary LLM SaaS (obviously copyright holder can do whatever they want with their code), however it requires external contributors and users of the code to ask for explicit permission to be able to legally do that. Exempted are only public research and non-commercial education purposes, per EU Directive 2019/790.
Note regarding Anthropic Claude - https://www.anthropic.com/legal/archive/bed577b7-02ee-4d59-bf38-8cfcbd45582e section 4 please opt-out of training through your account settings.
See …
> chore(license): add license; update readme and contribution guidelines
